### ISSUE TITLE
設定画面の項目のアイコン変更

### ISSUE THREAD

**Issue by senzaki2525** [RimlTempest/StampApp#102]
# タスク
設定画面の項目のアイコンをわかりやすい良いデザインのアイコンに変更する

## タスク達成条件

上記の条件を実装する。
githubへ`fix/icon/102`というブランチでpushする。
コードレビューを行いマージされたタイミングで達成

**Comment by kyosuke24** [comment]
プライバシーポリシーのアイコン案
admin_panel_settings_rounded
enhanced_encryption
