### ISSUE TITLE
合計スタンプ数の文字が四角い枠の中央にくるように修正

### ISSUE THREAD

**Issue by RimlTempest** [RimlTempest/StampApp#154]
# タスク
現在合計スタンプ数の文字が四角い枠の左上に寄ってるので中央にくるように修正する

## タスク達成条件

上記の条件を実装する。
githubへ`ブランチ`というブランチでpushする。
コードレビューを行いマージされたタイミングで達成

**Comment by RimlTempest** [comment]
![Uploading B3155A2B-2E58-4323-8D18-6BF56060AC7A.jpeg…]()

**Comment by RimlTempest** [comment]
![6D4A8C15-48F7-4F44-B99E-576CCE608C56](https://user-images.githubusercontent.com/38300385/125555406-7b7db763-968e-4cd0-80d9-500cff50ca48.jpeg)

**Comment by kyosuke24** [comment]
![totalpoint](https://user-images.githubusercontent.com/58577250/125885476-1b9cad67-8ff3-4780-9cf4-a7f005450d61.jpg)
