### ISSUE TITLE
スタンプ利用後のスタンプシートが更新されない不具合

### ISSUE THREAD

**Issue by zinNORI** [RimlTempest/StampApp#191]
# タスク
スタンプを9個集めた後スタンプを利用しても、スタンプシートのスタンプ画像が9個表示されっぱなしになり、（タスクキルして再起動で反映される）その状態でスタンプを読み込んでしまうと規定数以上のスタンプ画像表示となるためかエラー落ちするという問題が発生しているため、原因を突き止め修正する

## タスク達成条件

上記のバグを修正する。
githubへ`fix/stampSheetBug/191`というブランチでpushする。
コードレビューを行いマージされたタイミングで達成

**Comment by RimlTempest** [comment]
今までホーム画面で全処理してたところをQR画面にスタンプ処理を任せたことが原因ぽい
タスクキルで反映されるのはinitStateかinitで内容取得する処理を書いてるからできてるっぽい。

**Comment by RimlTempest** [comment]
@GanganGansoku に前実装してもらったスタンプ上限になった場合QR読み込みボタンをアラート呼び出しに切り替わるところがうまくいってないのも謎だ

**Comment by RimlTempest** [comment]
ChangeNotifier（vueでいうvuex的な）のようなstateの通知管理系を導入したほうがいいかなぁ

**Comment by RimlTempest** [comment]
この記事にあるように簡単に通知渡しが可能

https://qiita.com/agajo/items/50d5d7497d28730de1d3#6-changenotifier%E3%82%92provider%E3%81%A7%E4%B8%8B%E5%B1%A4%E3%81%AB%E6%B8%A1%E3%81%99%E6%9C%AC%E5%91%BD
