### ISSUE TITLE
全体を通してリファクタリング

### ISSUE THREAD

**Issue by RimlTempest** [RimlTempest/StampApp#224]
# タスク
コメントなどの確認と不必要なもののリファクタリングを行う

## タスク達成条件

上記の条件を実装する。
githubへ`clean/app/224`というブランチでpushする。
コードレビューを行いマージされたタイミングで達成

**Comment by zinNORI** [comment]
動作チェック
![スクリーンショット 2021-07-30 115201](https://user-images.githubusercontent.com/50894870/127592688-c52f7c91-8dd5-46d2-9f8a-0935b81fc986.png)
![スクリーンショット 2021-07-30 114954](https://user-images.githubusercontent.com/50894870/127592691-82a39e54-2a6f-4b5d-9f6f-864819a0e1bc.png)
![スクリーンショット 2021-07-30 115119](https://user-images.githubusercontent.com/50894870/127592693-e74b351e-c7bf-4f58-96f8-694b628fbf5a.png)
![スクリーンショット 2021-07-30 115141](https://user-images.githubusercontent.com/50894870/127592695-c95cb28f-79d9-42af-92d1-d0f7655adb34.png)

**Comment by shuuho** [comment]
リファクタリング後チェック
![image](https://user-images.githubusercontent.com/65703265/127592374-28391411-8b0e-4950-831f-69e19877d426.png)
![image](https://user-images.githubusercontent.com/65703265/127592533-c2b78ec8-4c8d-484e-8b47-5a91ac2b52b6.png)
![image](https://user-images.githubusercontent.com/65703265/127592546-bdbd230b-fc93-42c2-ba70-f1159c4bcf42.png)
![image](https://user-images.githubusercontent.com/65703265/127592631-09138125-c25b-45c2-af5c-af0811e79246.png)

**Comment by shuuho** [comment]
動作チェック！
![image](https://user-images.githubusercontent.com/65703265/127594002-601d0c09-7e0b-4220-afc5-a0333e51df13.png)
![image](https://user-images.githubusercontent.com/65703265/127594098-3ae23499-a625-448e-8a92-26fdaa545012.png)
![image](https://user-images.githubusercontent.com/65703265/127594118-7ba998a5-5ef8-4e70-9381-e8d5b0e26414.png)
![image](https://user-images.githubusercontent.com/65703265/127594145-2f9f4e57-1048-4ad7-8b5a-57d30882c4c7.png)

**Comment by keykimu** [comment]
動作チェック
![bandicam 2021-07-30 11-40-59-598](https://user-images.githubusercontent.com/44780741/127594877-7b33df8b-aded-4e00-805d-06dc75668b35.jpg)
![bandicam 2021-07-30 11-42-27-667](https://user-images.githubusercontent.com/44780741/127594883-5225a502-5167-44fd-a358-4ae629185e83.jpg)
![bandicam 2021-07-30 11-43-14-947](https://user-images.githubusercontent.com/44780741/127594884-5a0fadfc-5087-402e-93ce-0aa1399223eb.jpg)

**Comment by kyosuke24** [comment]
# 動作確認
スタンプ空のホーム画面
![def_home](https://user-images.githubusercontent.com/58577250/127595510-a1ff8c48-cfeb-4bb6-859f-40c78f9593fd.jpg)
スタンプ９個押されているホーム画面
![max_stamp](https://user-images.githubusercontent.com/58577250/127595571-7e25377a-19e3-4130-9249-13f883baf9ec.jpg)
９個のスタンプ消費後のスタンプ履歴画面
![stamp_his](https://user-images.githubusercontent.com/58577250/127595592-88686452-32b4-4307-86c0-8937b9fcc460.jpg)

**Comment by yoshida874** [comment]
動作チェック
![image](https://user-images.githubusercontent.com/45518040/127601836-bd2decf4-16c0-44ef-84d9-2b587baf8e6d.png)
![image](https://user-images.githubusercontent.com/45518040/127601849-6c777daf-5416-440e-8fec-9393de3ecc8f.png)
![image](https://user-images.githubusercontent.com/45518040/127601862-71d39d78-6312-440c-89ff-3bed96d5ef61.png)

**Comment by kensyuu1** [comment]
動作チェック
![chek1](https://user-images.githubusercontent.com/57424541/127604469-21a5b34c-9493-4ce5-a936-93eb676c2b66.png)
![chek2](https://user-images.githubusercontent.com/57424541/127604478-e6bf5d96-dd65-436f-8cd2-ddb030fbbbe7.png)
![chek3](https://user-images.githubusercontent.com/57424541/127604481-8482d03f-2c1e-497c-9a05-e82654fea4f9.png)

**Comment by shuuho** [comment]
一応、再度リファクタリング後の動作チェック問題無しです。
![image](https://user-images.githubusercontent.com/65703265/127608599-9340e091-bbb9-48df-9bb0-69e90419ea91.png)
![image](https://user-images.githubusercontent.com/65703265/127608764-9615112e-37f7-456c-aafa-ab4b65bd40cb.png)
![image](https://user-images.githubusercontent.com/65703265/127608794-d7b1d3fd-0b8b-4ac0-8d2b-265d968373f3.png)

**Comment by yamakou0808** [comment]
リファクタリング後動作確認
エミュレーター
![TEST1](https://user-images.githubusercontent.com/57611033/127610741-61a10abd-2e59-46bd-9ad5-d4d132cde234.png)
![TEST3](https://user-images.githubusercontent.com/57611033/127610744-62a57126-b2a6-47d7-bc8c-8d10135bf230.png)
![TEST2](https://user-images.githubusercontent.com/57611033/127610745-5d0911c3-db84-44b5-a19a-d414b32a07e0.png)

**Comment by senzaki2525** [comment]
動作チェック
![home10](https://user-images.githubusercontent.com/58577218/127619370-2656cdd3-bc92-4a26-a2b5-46172a1e0971.PNG)
![use](https://user-images.githubusercontent.com/58577218/127619374-1effffdd-fa5b-4f6f-b548-a92cfddee0ef.PNG)
![stamp9](https://user-images.githubusercontent.com/58577218/127619377-6727e417-4b6f-4000-8369-8caba0d6a0ab.PNG)
