### ISSUE TITLE
スタンプデータがあれば画像をスタンプとして表示するように、スタンプ表示一覧がわかりやすいよう修正

### ISSUE THREAD

**Issue by RimlTempest** [RimlTempest/StampApp#68]
# タスク
スタンプが今丸に囲まれた数字が表示されるようになっているので画像に置き換える
スタンプ一覧が今スタンプがない状態だと空欄表記でわかりにくいので初期スタンプ位置（丸に囲まれた数字だったり）を置きわかりやすいように修正
画像を用いるのでスタンプタップ時にスタンプ詳細ダイアログに画像を表示するようにも修正

## タスク達成条件

上記の条件を実装する。
githubへ`feature/detailImage/68`というブランチでpushする。
コードレビューを行いマージされたタイミングで達成

**Comment by GanganGansoku** [comment]
ダイアログに画像表示とスタンプのテキストを画像に入れ替え。
![Screenshot_20210527-152543](https://user-images.githubusercontent.com/57424509/119776817-5d3b3a80-bf00-11eb-9771-4a58bbfc3d6e.png)
![Screenshot_20210527-152809](https://user-images.githubusercontent.com/57424509/119776824-60362b00-bf00-11eb-88c5-060e9e6b5443.png)

**Comment by GanganGansoku** [comment]
スタンプの画像を花丸に置き換えテスト。
![Screenshot_20210527-153727](https://user-images.githubusercontent.com/57424509/119777706-827c7880-bf01-11eb-8d02-a2bc99a71d7e.png)

**Comment by GanganGansoku** [comment]
外枠の青線削除。
![Screenshot_20210527-154339](https://user-images.githubusercontent.com/57424509/119778550-a096a880-bf02-11eb-96f0-7181af2f0a11.png)
