### ISSUE TITLE
ホーム画面のFigmaを修正する

### ISSUE THREAD

**Issue by RimlTempest** [RimlTempest/StampApp#69]
# タスク
今後的にスタンプ情報を複数保持しページング方式で表示できるようにする予定もあり #68 のほうでGridデザインを作ってもらっているのでこれを参考にしホーム画面のデザインを再考する。

## タスク達成条件

Figmaでホーム画面の再考をし上記の内容を達成する。
全員で確認し @RimlTempest が許可したタイミングで達成

**Comment by kyosuke24** [comment]
ホームのデザイン（仮）
![home](https://user-images.githubusercontent.com/58577250/120262216-5895ce00-c2d4-11eb-8569-d59a6832b5cb.jpg)

**Comment by shuuho** [comment]
ホーム画面デザイン３（仮）
![image](https://user-images.githubusercontent.com/65703265/120262394-998de280-c2d4-11eb-9c61-fdc6f21c208a.png)

**Comment by yamakou0808** [comment]
下のDBサンプルボタンは消えるていで
![image](https://user-images.githubusercontent.com/57611033/120263446-a4497700-c2d6-11eb-93b3-6cea1e71b8e5.png)

**Comment by kyosuke24** [comment]
少し修正
![ホーム2](https://user-images.githubusercontent.com/58577250/120409629-4bd4b100-c38c-11eb-9299-f58d4b1d6189.jpg)

**Comment by kensyuu1** [comment]
ホームのデザイン(仮)
![ホーム(仮)](https://user-images.githubusercontent.com/57424541/120411277-7e33dd80-c38f-11eb-8d26-f1d505fbb864.png)

**Comment by yamakou0808** [comment]
6月1日の修正
修正内容
　文字統一
　スタンプカードの移動ボタン配置
　その他デザインをブラッシュアップ
![image](https://user-images.githubusercontent.com/57611033/120419338-3ae06b80-c39d-11eb-9b3f-b2905215a49c.png)

**Comment by senzaki2525** [comment]
6/8　Home画面の修正
内容
スワイプでスタンプカードの変更ができるようなデザインにした
![修正案](https://user-images.githubusercontent.com/58577218/121107420-dca30500-c842-11eb-80d6-4100871c8eb0.PNG)

**Comment by senzaki2525** [comment]
完成。スワイプでほかの画面に遷移する形にする。
![Home](https://user-images.githubusercontent.com/58577218/121467605-51697100-c9f4-11eb-8315-e5405a854759.PNG)
