### ISSUE TITLE
読み込み用のサンプルQRコード作成

### ISSUE THREAD

**Issue by RimlTempest** [RimlTempest/StampApp#77]
# タスク
QRコード読み込みのテストのためも含めてStampモデルの内容を含んだjsonをQRコード化しこのissueに貼る

## タスク達成条件

上記のQRを生成する。

**Comment by RimlTempest** [comment]
QRの中身もどうなっているか生成した時の内容とQRリーダー（なんのアプリ、ツールでもいい）で読み取った時の内容のスクショを貼ってほしい

**Comment by keykimu** [comment]
生成時
![bandicam 2021-06-08 12-40-26-865](https://user-images.githubusercontent.com/44780741/121120053-c489b080-c857-11eb-97d5-d9e4a42a700d.jpg)
iphone標準カメラでの読み取り
![WvFZDztJ](https://user-images.githubusercontent.com/44780741/121120057-c784a100-c857-11eb-90dc-a9f6835e5f7f.jpg)
こんな感じでいいのかな？

**Comment by RimlTempest** [comment]
data, stampNum, createdAtだけでよくない？
id, deletedFlg, deletedAtってDBに関連するものだしgetDate, getTimeについてはQRを読み込んだ日付時間でしょ？

**Comment by keykimu** [comment]
![bandicam 2021-06-08 13-32-23-527](https://user-images.githubusercontent.com/44780741/121123518-52689a00-c85e-11eb-860d-5db5bc672c53.jpg)
![qcoO8H5Z](https://user-images.githubusercontent.com/44780741/121123525-5694b780-c85e-11eb-85e9-201f7ecf14b1.jpg)

**Comment by RimlTempest** [comment]
createdAtはDateTime型を参考にお願い
日付だけじゃなくて時間も必要なので

**Comment by keykimu** [comment]
![bandicam 2021-06-08 14-36-38-875](https://user-images.githubusercontent.com/44780741/121128973-35849480-c867-11eb-90a8-dc3142127fd3.jpg)
![HI4P9WDj](https://user-images.githubusercontent.com/44780741/121128983-39181b80-c867-11eb-92cc-4b05af4926ec.jpg)

**Comment by keykimu** [comment]
![bandicam 2021-06-10 13-42-14-332](https://user-images.githubusercontent.com/44780741/121466294-28e07780-c9f2-11eb-935e-95f6250a8454.jpg)
![3o81B4Bz](https://user-images.githubusercontent.com/44780741/121466413-5decca00-c9f2-11eb-9147-62f36fe4b9b0.jpg)
